package ib

var REQUEST ReqStruct

type ReqStruct struct {
	CODE ReqCodeStruct 
	VERSION ReqVersionStruct
}

type ReqCodeStruct struct {
	MARKET_DATA int64
	CONTRACT_DATA int64
	HISTORICAL_DATA int64
}

type ReqVersionStruct struct {
	MARKET_DATA int64
	CONTRACT_DATA int64
	HISTORICAL_DATA int64
}

func init() {
	REQUEST.CODE.MARKET_DATA = 1
	REQUEST.CODE.CONTRACT_DATA = 9
	REQUEST.CODE.HISTORICAL_DATA = 20 

	REQUEST.VERSION.MARKET_DATA = 10
	REQUEST.VERSION.CONTRACT_DATA = 7
	REQUEST.VERSION.HISTORICAL_DATA = 5
}


