package ib

var RESPONSE ResponseHeader

type ResponseHeader struct {
	CODE ResponseCodes
}

type ResponseCodes struct {
	ERR_MSG                 string
	CONTRACT_DATA           string
	TICK_PRICE              string
	TICK_SIZE               string
	TICK_OPTION_COMPUTATION string
	TICK_GENERIC            string
	TICK_STRING             string
	TICK_EFP                string
	TICK_SNAPSHOT_END       string
	MARKET_DATA_TYPE        string
	HISTORICAL_DATA         string
	ACCOUNT_VALUE           string
	PORTFOLIO_VALUE         string
	ACCOUNT_UPDATE_TIME     string
}

func init() {
	RESPONSE.CODE.ERR_MSG = "4"
	RESPONSE.CODE.CONTRACT_DATA = "10"
	RESPONSE.CODE.TICK_PRICE = "1"
	RESPONSE.CODE.TICK_SIZE = "2"
	RESPONSE.CODE.TICK_OPTION_COMPUTATION = "21"
	RESPONSE.CODE.TICK_GENERIC = "45"
	RESPONSE.CODE.TICK_STRING = "46"
	RESPONSE.CODE.TICK_EFP = "47"
	RESPONSE.CODE.TICK_SNAPSHOT_END = "57"
	RESPONSE.CODE.MARKET_DATA_TYPE = "58"
	RESPONSE.CODE.HISTORICAL_DATA = "17"
	RESPONSE.CODE.ACCOUNT_VALUE = "6"
	RESPONSE.CODE.PORTFOLIO_VALUE = "7"
	RESPONSE.CODE.ACCOUNT_UPDATE_TIME = "8"
}
